version: '3.8'
services:
    dev:
        container_name: tagme_api_fe
        image: tagme-api-fe:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 8080:8080
        networks:
            - fe-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
  fe-network: